language: python
python:
    - 3.8
    - 3.9

# what branches should be evaluated
branches:
    only:
        - main

# list of commands to run to setup the environment
install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - python setup.py install

# a list of commands to run before the main script
before_script:
    - "flake8 cooksmart"

# the actual commands to run
script:
    - coverage run -m unittest discover cooksmart/tests

# generate a coverage report to send to back to user
after_success:
    - coverage report
    - coveralls
